- project:
    templates:
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - release-notes-jobs
      - periodic-stable-jobs-neutron
      - publish-openstack-sphinx-docs
      - check-requirements
    check:
      jobs:
        - networking-odl-grenade:
            voting: false
            branches: ^(?!(driverfixes|stable/(mitaka|newton))).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-carbon
        - networking-odl-tempest-nitrogen
        - networking-odl-tempest-oxygen
        - networking-odl-tempest-carbon-multinode:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-nitrogen-multinode:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-tempest-oxygen-multinode:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - networking-odl-rally-carbon:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-nitrogen:
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-oxygen:
            voting: false
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-fullstack-carbon:
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-carbon:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-fullstack-nitrogen:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-nitrogen:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-fullstack-oxygen:
            voting: false
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-oxygen:
            voting: false
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-tox-pep8:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py35:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-cover:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
    gate:
      jobs:
        - networking-odl-rally-carbon:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-rally-nitrogen:
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-fullstack-carbon:
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-carbon:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-fullstack-nitrogen:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - networking-odl-functional-nitrogen:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-tox-pep8:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py35:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-cover:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
    post:
      jobs:
        - publish-openstack-python-branch-tarball:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
    periodic:
      jobs:
        - openstack-tox-py35-with-neutron-lib-master:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
    periodic-stable:
      jobs:
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn
        - openstack-tox-py27:
            required-projects:
              - openstack/ceilometer
              - openstack/neutron-fwaas
              - openstack/neutron-lbaas
              - openstack/networking-l2gw
              - openstack/networking-sfc
              - openstack/networking-bgpvpn

